version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  app:
    image: my-node-app
    ports:
      - 8080:3333
    volumes:
      - .:/usr/src/app         # เชื่อมโค้ดในเครื่องเข้ากับ Container
      - /usr/src/app/node_modules # ยกเว้น node_modules ไม่ให้ทับกัน